# Generated by Django 4.2.5 on 2023-09-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsmodels',
            name='qr1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
