# Generated by Django 4.2.5 on 2023-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcecountsql',
            name='MAX',
            field=models.DateField(blank=True, null='True', verbose_name='Дата платежа'),
        ),
    ]
