# Generated by Django 4.2.5 on 2023-09-19 11:30

import connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_Name', models.CharField(max_length=250, verbose_name='Фамилия, Имя, Отчество')),
                ('pr_phone', models.CharField(max_length=20, verbose_name='Ваш телефон')),
                ('pr_email', models.EmailField(max_length=150, verbose_name='Ваш е-mail ')),
                ('pr_reg_city', models.CharField(max_length=250, verbose_name='Город')),
                ('pr_reg_street', models.CharField(max_length=200, verbose_name='Улица')),
                ('pr_reg_home', models.CharField(max_length=10, verbose_name='Дом')),
                ('pr_reg_flat', models.PositiveIntegerField(max_length=10, verbose_name='Квартира')),
                ('pr_doc_attorney', models.ImageField(upload_to=connect.models.user_dir_path, verbose_name='Копия паспорта')),
                ('pr_doc_ownership', models.ImageField(upload_to=connect.models.user_dir_path, verbose_name='Документы, подтверждающие право собственности')),
                ('pr_doc_family', models.ImageField(upload_to=connect.models.user_dir_path, verbose_name='Справка о составе семьи')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы на перегистрацию',
            },
        ),
    ]
