# Generated by Django 4.2.5 on 2023-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=248, verbose_name='Пользователь')),
                ('email_pole', models.EmailField(max_length=248, verbose_name='Почта')),
                ('lic1_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №1')),
                ('lic2_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №2')),
                ('lic3_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №3')),
                ('lic4_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №4')),
                ('lic5_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №5')),
                ('lic6_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №6')),
                ('lic11_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №1-Доп поле')),
                ('lic12_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №2-Доп поле')),
                ('lic13_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №3-Доп поле')),
                ('lic14_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №4-Доп поле')),
                ('lic15_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №5-Доп поле')),
                ('lic16_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №6-Доп поле')),
            ],
        ),
    ]
