# Generated by Django 4.2.5 on 2023-11-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvit', '0002_alter_receipt_options_alter_receipt_lic11_pole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopPapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=248, verbose_name='Пользователь')),
                ('email_pole', models.EmailField(max_length=248, verbose_name='Почта')),
                ('lic1_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №1')),
                ('lic2_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №2')),
                ('lic3_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №3')),
                ('lic4_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №4')),
                ('lic5_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №5')),
                ('lic6_pole', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Лицевой №6')),
                ('lic11_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №1-Отказ от бумажной квитанции')),
                ('lic12_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №2-Отказ от бумажной квитанции')),
                ('lic13_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №3-Отказ от бумажной квитанции')),
                ('lic14_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №4-Отказ от бумажной квитанции')),
                ('lic15_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №5-Отказ от бумажной квитанции')),
                ('lic16_pole', models.BooleanField(blank=True, null=True, verbose_name='Лицевой №6-Отказ от бумажной квитанции')),
            ],
        ),
    ]
