# Generated by Django 4.2.5 on 2023-11-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='gapTimeDown',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Промежуток времени Конец'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='gapTimeUp',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Промежуток времени Начало'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_five',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_four',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_seven',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_six',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='optMaps_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица или поселок с номером'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='gapTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промежуток времени Не использовать'),
        ),
    ]
