# Generated by Django 4.2.5 on 2023-09-19 11:30

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTimes', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('questionItself', models.TextField(verbose_name='Ваш вопрос')),
                ('departmentReplied', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Асу'), (2, 'Отдел по работе с юр. лицами'), (3, 'Отдел ПТО'), (4, 'Отдел закупок')], null=True, verbose_name='Отдел')),
                ('answerToTheQuestion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопрос всем',
            },
        ),
        migrations.CreateModel(
            name='questionAbonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberIsSet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя автора')),
                ('dataTimes', models.DateField(default=datetime.datetime.now)),
                ('questionItself', models.TextField(verbose_name='Ваш вопрос')),
                ('answerToTheQuestion', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы абоненскому',
            },
        ),
    ]
