# Generated by Django 4.2.5 on 2023-09-19 11:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModelDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='info/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '2023',
                'verbose_name_plural': 'за 2023',
            },
        ),
        migrations.CreateModel(
            name='InfoModelDocbeforeLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='info/2021/')),
            ],
            options={
                'verbose_name': '2021',
                'verbose_name_plural': 'за 2021',
            },
        ),
        migrations.CreateModel(
            name='InfoModelDocLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='info/2022/')),
            ],
            options={
                'verbose_name': '2022',
                'verbose_name_plural': 'за 2022',
            },
        ),
        migrations.CreateModel(
            name='InfoModelDocnazLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='info/2020/')),
            ],
            options={
                'verbose_name': '2020',
                'verbose_name_plural': 'за 2020',
            },
        ),
        migrations.CreateModel(
            name='WaterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('pagesText', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='WaterModelDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='waterdoc/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Документы по воде',
                'verbose_name_plural': 'Водоснабжение Приложение',
            },
        ),
    ]
