# Generated by Django 4.2.5 on 2023-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterModelDocDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('fileTypes', models.FileField(upload_to='waterdoc/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Документы по воде',
                'verbose_name_plural': 'Водоотведени Приложение',
            },
        ),
    ]
