# Generated by Django 4.2.5 on 2023-09-26 15:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_watermodeldocdisposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='indxpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('pagesText', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Другие разделы',
                'verbose_name_plural': 'Другие',
            },
        ),
    ]
