# Generated by Django 4.2.5 on 2023-10-03 13:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_indxpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('pagesText', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
