# Generated by Django 4.2.5 on 2023-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debtCHModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ п/п')),
                ('personalAccount', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ л. счета')),
                ('residentialAdress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес должника')),
                ('debt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
            },
        ),
        migrations.CreateModel(
            name='debtURModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ п/п')),
                ('personalAccount', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ л. счета')),
                ('personalName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('residentialAdress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес должника')),
                ('debt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники Упр.',
            },
        ),
        migrations.CreateModel(
            name='tamponingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ п/п')),
                ('personalAccount', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='№ л. счета')),
                ('residentialAdress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес должника')),
                ('debt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники на тампонирование',
            },
        ),
    ]
