# Generated by Django 4.2.4 on 2023-08-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InduExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ls', models.CharField(max_length=50, null=True, verbose_name='Лицевой счет')),
                ('name_dom', models.CharField(max_length=50, null=True, verbose_name='Номер дома')),
                ('name_kv', models.CharField(max_length=50, null=True, verbose_name='Квартира')),
                ('codsch_hv1', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_1')),
                ('hv1_data', models.CharField(max_length=50, null=True, verbose_name='Показание ХВ_1')),
                ('codsh_gv1', models.CharField(max_length=50, verbose_name='Код счетчика ГВ_1')),
                ('gv1_data', models.CharField(max_length=50, null=True, verbose_name='Показания ГВ_1')),
                ('codsch_hv2', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_2')),
                ('hv2_data', models.CharField(max_length=50, null=True, verbose_name='Показание ХВ_2')),
                ('codsch_gv2', models.CharField(max_length=20, null=True, verbose_name='Код счетчика ГВ_2')),
                ('gv2_data', models.CharField(max_length=50, verbose_name='Показание ГВ_2')),
                ('codsch_hv3', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_3')),
                ('hv3_data', models.CharField(max_length=50, null=True, verbose_name='Показакние ХВ_3')),
                ('codsch_gv3', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ГВ_3')),
                ('gv3_data', models.CharField(max_length=50, null=True, verbose_name='Показания ГВ_3')),
                ('codsch_hv4', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_4')),
                ('hv_data', models.CharField(max_length=50, null=True, verbose_name='Показания ХВ_4')),
                ('codsh_gv4', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ГВ_4')),
                ('gv4_data', models.CharField(max_length=50, null=True, verbose_name='Показание ГВ_4')),
            ],
        ),
        migrations.CreateModel(
            name='InduImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ls', models.CharField(max_length=50, null=True, verbose_name='Лицевой счет')),
                ('name_dom', models.CharField(max_length=50, null=True, verbose_name='Номер дома')),
                ('name_kv', models.CharField(max_length=50, null=True, verbose_name='Квартира')),
                ('codsch_hv1', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_1')),
                ('hv1_data', models.CharField(max_length=50, null=True, verbose_name='Показание ХВ_1')),
                ('codsh_gv1', models.CharField(max_length=50, verbose_name='Код счетчика ГВ_1')),
                ('gv1_data', models.CharField(max_length=50, null=True, verbose_name='Показания ГВ_1')),
                ('codsch_hv2', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_2')),
                ('hv2_data', models.CharField(max_length=50, null=True, verbose_name='Показание ХВ_2')),
                ('codsch_gv2', models.CharField(max_length=20, null=True, verbose_name='Код счетчика ГВ_2')),
                ('gv2_data', models.CharField(max_length=50, verbose_name='Показание ГВ_2')),
                ('codsch_hv3', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_3')),
                ('hv3_data', models.CharField(max_length=50, null=True, verbose_name='Показакние ХВ_3')),
                ('codsch_gv3', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ГВ_3')),
                ('gv3_data', models.CharField(max_length=50, null=True, verbose_name='Показания ГВ_3')),
                ('codsch_hv4', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ХВ_4')),
                ('hv_data', models.CharField(max_length=50, null=True, verbose_name='Показания ХВ_4')),
                ('codsh_gv4', models.CharField(max_length=50, null=True, verbose_name='Код счетчика ГВ_4')),
                ('gv4_data', models.CharField(max_length=50, null=True, verbose_name='Показание ГВ_4')),
            ],
        ),
    ]
