# Generated by Django 4.2.4 on 2023-08-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inducations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='induexport',
            options={'verbose_name': 'Лицевой', 'verbose_name_plural': 'Лицевые выгрузить в ермак'},
        ),
        migrations.AlterModelOptions(
            name='induimport',
            options={'verbose_name': 'Лицевой', 'verbose_name_plural': 'Лицевые загрузить'},
        ),
    ]
