# Generated by Django 4.2.4 on 2023-08-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inducations', '0002_alter_induexport_options_alter_induimport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='induexport',
            options={'verbose_name': 'Лицевой', 'verbose_name_plural': 'MDK Лицевые выгрузить в ермак'},
        ),
        migrations.AlterModelOptions(
            name='induimport',
            options={'verbose_name': 'Лицевой', 'verbose_name_plural': 'MKD Лицевые загрузить'},
        ),
    ]
