# Generated by Django 4.2.4 on 2023-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inducations', '0003_alter_induexport_options_alter_induimport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InduExportCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ls', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лицевой счет')),
                ('name_dom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома')),
                ('name_kv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('codsch_hv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_1')),
                ('hv1_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1')),
                ('codsh_gv1', models.CharField(max_length=50, verbose_name='Код счетчика ГВ_1')),
                ('gv1_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1')),
                ('codsch_hv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_2')),
                ('hv2_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2')),
                ('codsch_gv2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код счетчика ГВ_2')),
                ('gv2_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2')),
                ('codsch_hv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_3')),
                ('hv3_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3')),
                ('codsch_gv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_3')),
                ('gv3_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3')),
                ('codsch_hv4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_4')),
                ('hv_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4')),
                ('codsh_gv4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_4')),
                ('gv4_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4')),
            ],
            options={
                'verbose_name': 'Лицевой',
                'verbose_name_plural': 'ЧС Переданные',
            },
        ),
        migrations.CreateModel(
            name='InduExportSela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ls', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лицевой счет')),
                ('name_dom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома')),
                ('name_kv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('codsch_hv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_1')),
                ('hv1_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1')),
                ('codsh_gv1', models.CharField(max_length=50, verbose_name='Код счетчика ГВ_1')),
                ('gv1_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1')),
                ('codsch_hv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_2')),
                ('hv2_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2')),
                ('codsch_gv2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код счетчика ГВ_2')),
                ('gv2_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2')),
                ('codsch_hv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_3')),
                ('hv3_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3')),
                ('codsch_gv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_3')),
                ('gv3_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3')),
                ('codsch_hv4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_4')),
                ('hv_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4')),
                ('codsh_gv4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_4')),
                ('gv4_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4')),
            ],
            options={
                'verbose_name': 'Лицевой',
                'verbose_name_plural': 'Села Переданные',
            },
        ),
        migrations.AlterModelOptions(
            name='induexport',
            options={'verbose_name': 'Лицевой', 'verbose_name_plural': 'MDK Переданные'},
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_gv2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код счетчика ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_gv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_hv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_hv2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_hv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsch_hv4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_4'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='codsh_gv4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv1_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv2_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv3_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv4_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv1_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv2_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv3_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='id_ls',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='name_dom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='name_kv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
    ]
