# Generated by Django 4.2.5 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inducations', '0004_induexportch_induexportsela_alter_induexport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='induexport',
            name='codsh_gv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='codsh_gv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induexportsela',
            name='codsh_gv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_gv2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код счетчика ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_gv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_hv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_hv2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_hv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsch_hv4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ХВ_4'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsh_gv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='codsh_gv4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код счетчика ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='gv1_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='gv2_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='gv3_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='gv4_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='hv1_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='hv2_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='hv3_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='hv_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='id_ls',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='name_dom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='induimport',
            name='name_kv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
    ]
