# Generated by Django 4.2.5 on 2023-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inducations', '0009_alter_induexportsela_gv1_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='induexport',
            name='gv1_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv2_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv3_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='gv4_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv1_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv2_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv3_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induexport',
            name='hv_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='gv1_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_1'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='gv2_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_2'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='gv3_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ГВ_3'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='gv4_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ГВ_4'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='hv1_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_1'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='hv2_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показание ХВ_2'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='hv3_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показакние ХВ_3'),
        ),
        migrations.AlterField(
            model_name='induexportch',
            name='hv_data',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Показания ХВ_4'),
        ),
    ]
